#! /usr/bin/env python
# encoding: utf-8

bld.program(
	packages      = 'msgpack',
	target        = 'simple',
	uselib        = 'GLIB MSGPACK',
	source        = ['simple.vala'],
	vapi_dirs     = ['../']
	)
